newPRWelcomeComment: >
  Hello,Thanks for opening this PR. Safety note: You're submitting your changes with YOUR OWN IDENTITY, which is probably not good for your anonymity. Unless you're OK with this, please consider submit your changes as beyondgfw beyond.gfw.limit@gmail.com.
